services:
  postgres:
    image: postgres:16
    container_name: desafio-lab-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: desafio_lab
    ports:
      - "5433:5432"
    volumes:
      - desafio_lab_pgdata:/var/lib/postgresql/data
    networks:
      - desafio-lab

networks:
  desafio-lab:
    name: desafio-lab-network

volumes:
  desafio_lab_pgdata:
    name: desafio-lab-pgdata
